services:
  homepage:
    container_name: visibility-dashboard
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GATEWAY_SERVER_URL=${GATEWAY_SERVER_URL}
    ports:
      - ${PORT:-80}:80
      - ${SSL_PORT:-443}:443
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    volumes:
      - ${SSL_CERTIFICATE_PATH:?err}:/etc/nginx/ssl/cert.pem
      - ${SSL_KEY_PATH:?err}:/etc/nginx/ssl/key.pem
      - ${SSL_CHAIN_PATH:?err}:/etc/nginx/ssl/chain.pem
