name: Build and Deploy (staging)

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack and Use Latest Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Configure Environment Variables
        run: |
          echo "VITE_APP_VERSION=v0.2.0" >> .env
          echo "GENERATE_SOURCEMAP=false" >> .env
          echo "PUBLIC_URL=${{ vars.PUBLIC_URL }}" >> .env
          echo "VITE_APP_BASE_NAME=/dashboard" >> .env
          echo "VITE_APP_GATEWAY_SERVER_URL=${{ vars.GATEWAY_SERVER_URL }}" >> .env
          echo "VITE_APP_TELEMETRY_API=${{ vars.TELEMETRY_API }}" >> .env

      - name: Install dependencies
        run: |
          yarn install

      - name: Build project
        run: |
          yarn build

      - name: Prepare build for deployment
        run: |
          mkdir -p build_output
          mkdir -p build_output/artifacts

          mv build/* build_output/artifacts/
          mv nginx/ build_output/nginx/
          mv scripts/ build_output/scripts/
          mv Dockerfile.nginx build_output/Dockerfile
          mv .gitignore build_output/.gitignore
          mv deploy.sh build_output/deploy.sh

      - name: Set up Git for commit
        uses: qoomon/actions--setup-git@v1
        with:
          user: bot

      - name: Commit and Push to Build Branch
        run: |
          git checkout --orphan build/staging
          git rm -rf .
          mv build_output/* .
          mv build_output/.gitignore .gitignore

          timestamp=$(date +"%Y-%m-%d %H:%M:%S (%Z)")

          git add .
          git commit -m "🚀 Build deployed at ${timestamp}"
          git push origin build --force
