name: Deploy to Staging Server

on:
  workflow_run:
    workflows:
      - Build and Deploy (staging)
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    environment:
      name: staging
      url: https://staging.smswithoutborders.com:18550
    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            set -e

            echo "============================"
            echo "🚀 Fetching all branches ..."
            echo "============================"
            cd ${{ secrets.PROJECT_PATH }}
            if ! git fetch --all; then
              echo "❌ Error fetching branches!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Branch fetch complete"
            echo "==============================="

            echo "============================"
            echo "🚀 Switching to build/staging branch ..."
            echo "============================"
            if ! git checkout build/staging; then
              echo "❌ Error switching to build/staging branch!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Switched to build/staging branch"
            echo "==============================="

            echo "============================"
            echo "🚀 Updating repository ..."
            echo "============================"
            if ! git pull; then
              echo "❌ Error updating repository!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Repository update complete"
            echo "==============================="

            echo "========================="
            echo "🚀 Building project ..."
            echo "========================="
            if ! ${{ secrets.BUILD_CMD }}; then
              echo "❌ Error building project!"
              exit 1
            fi
            echo "==========================="
            echo "✅ Project build complete"
            echo "==========================="

            echo "============================="
            echo "Cleaning up staging builds ..."
            echo "============================="
            if ! ${{ secrets.CLEANUP_CMD }}; then
              echo "❌ Error cleaning up builds!"
              exit 1
            fi
            echo "============================="
            echo "✅ Cleanup complete"
            echo "============================="
